### ISSUE TITLE
Infinite loop on processing a changefile with an unknown distribution

### ISSUE THREAD

**Issue by gera** [shartge/mini-dinstall#2]
On uploading a changefile with the distribution set to an unknown/unexpected value, minid-install goes into an infinite loop trying to process the same changefile over and over again.

If it's set to email on errors, it *will* cause a real flood of email.

**Comment by gera** [comment]
Example log when this occurs:

```
Oct 19 04:42:28 mini-dinstall [140606596712192] ERROR: Unable to install "/var/www/debian-xenial/mini-dinstall/incoming/grafana_5.3.1_amd64.changes"; adding to screwed list
Traceback (most recent call last):
  File "/usr/bin/mini-dinstall", line 678, in _daemonize
    self._install_changefile(changefilename, changefile, doing_reprocess)
  File "/usr/bin/mini-dinstall", line 584, in _install_changefile
    raise DinstallException('Unknown distribution "%s" in \"%s\"' % (dist, changefilename,))
DinstallException: 'Unknown distribution "trusty" in "/var/www/debian-xenial/mini-dinstall/incoming/grafana_5.3.1_amd64.changes"'
Oct 19 04:42:29 mini-dinstall [140606596712192] ERROR: Unable to install "/var/www/debian-xenial/mini-dinstall/incoming/grafana_5.3.1_amd64.changes"; adding to screwed list
Traceback (most recent call last):
  File "/usr/bin/mini-dinstall", line 678, in _daemonize
    self._install_changefile(changefilename, changefile, doing_reprocess)
  File "/usr/bin/mini-dinstall", line 584, in _install_changefile
    raise DinstallException('Unknown distribution "%s" in \"%s\"' % (dist, changefilename,))
DinstallException: 'Unknown distribution "trusty" in "/var/www/debian-xenial/mini-dinstall/incoming/grafana_5.3.1_amd64.changes"'
Oct 19 04:42:29 mini-dinstall [140606596712192] ERROR: Unable to install "/var/www/debian-xenial/mini-dinstall/incoming/grafana_5.3.1_amd64.changes"; adding to screwed list
Traceback (most recent call last):
  File "/usr/bin/mini-dinstall", line 678, in _daemonize
    self._install_changefile(changefilename, changefile, doing_reprocess)
  File "/usr/bin/mini-dinstall", line 584, in _install_changefile
    raise DinstallException('Unknown distribution "%s" in \"%s\"' % (dist, changefilename,))
DinstallException: 'Unknown distribution "trusty" in "/var/www/debian-xenial/mini-dinstall/incoming/grafana_5.3.1_amd64.changes"'
Oct 19 04:42:29 mini-dinstall [140606596712192] ERROR: Unable to install "/var/www/debian-xenial/mini-dinstall/incoming/grafana_5.3.1_amd64.changes"; adding to screwed list
```

(this goes on till mini-dinstall is killed)

**Comment by shartge** [comment]
Thank you for finding and fixing this problem, but this repository here on Github is just an old mirror of the upstream repository.

While I will merge the PR here for myself, it would be very very nice if you could report the bug and the solution in the Debian BTS for mini-dinstall.
